# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:

  test:
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Workspace Dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Build (checks .ts types)
          command: yarn build
          when: always

      - run:
          name: Run Linter
          command: yarn run lint:ci
          when: always

      - run:
          name: Run Tests
          command: yarn test:ci
          when: always

      - run:
          name: Check Code Formatting
          command: yarn prettier:ci
          when: always

      - store_test_results:
          path: reports
          when: always

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2.1
  unit_test:
    jobs:
      - test
